services:

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: local
      POSTGRES_USER: postgres_usr
      POSTGRES_PASSWORD: postgres_pass
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:7.5
    user: root
    restart: no
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin_pass
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin_storage:/var/lib/pgadmin
    depends_on:
      - db

  server:
    build:
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres_usr
      POSTGRES_HOST: db
      POSTGRES_DB: local
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_PORT: 5432
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    command: /app/entrypoint.sh
    depends_on:
      - db